- name: gp
  mountPath: /gp
- name: data
  mountPath: /ericsson/tor/data
- name: mdt
  mountPath: /etc/opt/ericsson/ERICmodeldeployment
- name: dumps
  mountPath: /ericsson/enm/dumps
- name: shared
  mountPath: /home/shared
- name: norollback
  mountPath: /ericsson/no_rollback
- name: pm1
  mountPath: /ericsson/pmic1
- name: pm2
  mountPath: /ericsson/pmic2
