- name: gp
  configMap:
    name: gpcloud
- name: data
  persistentVolumeClaim:
    claimName: data
- name: pm1
  persistentVolumeClaim:
    claimName: pm1
- name: pm2
  persistentVolumeClaim:
    claimName: pm2
- name: dumps
  persistentVolumeClaim:
    claimName: hcdumps
- name: mdt
  persistentVolumeClaim:
    claimName: mdt
- name: shared
  persistentVolumeClaim:
    claimName: home
- name: norollback
  persistentVolumeClaim:
    claimName: norollback
- name: enm-version-configmap
  configMap:
    name: eric-enm-version-configmap
